CREATE TABLE catest_0011 (
	"County Code" VARCHAR(2) NOT NULL, 
	"District Code" VARCHAR(5) NOT NULL, 
	"School Code" VARCHAR(7) NOT NULL, 
	"Charter Number" VARCHAR(4) NOT NULL, 
	"Test Year" VARCHAR(4) NOT NULL, 
	"Subgroup ID" VARCHAR(1) NOT NULL, 
	"Test Type" VARCHAR(1) NOT NULL, 
	"CAPA Assessment Level" VARCHAR(1) NOT NULL, 
	"Total STAR Enrollment" VARCHAR(7) NOT NULL, 
	"Total Tested At Entity Level" VARCHAR(7) NOT NULL, 
	"Total Tested At Subgroup Level" VARCHAR(7) NOT NULL, 
	"Grade" VARCHAR(2) NOT NULL, 
	"Test Id" VARCHAR(2) NOT NULL, 
	"STAR Reported Enrollment/CAPA Eligible" VARCHAR(6), 
	"Students Tested" VARCHAR(6) NOT NULL, 
	"Percent Tested" VARCHAR(4), 
	"Mean Scale Score" VARCHAR(5), 
	"Percentage Advanced" VARCHAR(2), 
	"Percentage Proficient" VARCHAR(2), 
	"Percentage At Or Above Proficient" VARCHAR(2), 
	"Percentage Basic" VARCHAR(2), 
	"Percentage Below Basic" VARCHAR(2), 
	"Percentage Far Below Basic" VARCHAR(2), 
	"Students with Scores" VARCHAR(6) NOT NULL, 
	"CMA/STS Average Percent Correct" VARCHAR(2)
);
